DISEASE_INFO = {
    "Fungal infection": "Keep the affected area clean and dry. Consult a dermatologist if needed.",
    "Allergy": "Avoid triggers, stay hydrated, and consult a doctor for anti-allergic treatment.",
    "GERD": "Avoid spicy and oily food. Do not lie down immediately after meals.",
    "Chronic cholestasis": "Please consult a liver specialist for proper evaluation.",
    "Drug Reaction": "Seek medical advice immediately if the reaction is severe.",
    "Peptic ulcer disease": "Avoid spicy foods and painkillers unless prescribed.",
    "AIDS": "Please consult an infectious disease specialist for confirmatory evaluation.",
    "Diabetes": "Monitor blood sugar, follow diet control, and exercise regularly.",
    "Gastroenteritis": "Drink fluids and oral rehydration solution. Consult a doctor if symptoms worsen.",
    "Bronchial Asthma": "Avoid dust and allergens. Use inhalers if prescribed.",
    "Hypertension": "Reduce salt, monitor blood pressure, and manage stress.",
    "Migraine": "Rest in a quiet room, stay hydrated, and avoid stress triggers.",
    "Cervical spondylosis": "Maintain posture and seek orthopedic consultation if pain persists.",
    "Paralysis (brain hemorrhage)": "Seek emergency medical care immediately.",
    "Jaundice": "Please consult a doctor and maintain hydration.",
    "Malaria": "Seek medical treatment quickly and maintain fluid intake.",
    "Chicken pox": "Rest well, isolate if needed, and avoid scratching rashes.",
    "Dengue": "Drink plenty of fluids and seek urgent medical evaluation.",
    "Typhoid": "Use safe drinking water and consult a doctor for treatment.",
    "hepatitis A": "Take rest and avoid oily foods.",
    "Hepatitis B": "Consult a liver specialist for further tests and treatment.",
    "Hepatitis C": "Seek medical evaluation for antiviral treatment options.",
    "Hepatitis D": "Consult a specialist for liver care.",
    "Hepatitis E": "Hydrate well and seek medical care.",
    "Alcoholic hepatitis": "Avoid alcohol completely and seek urgent medical support.",
    "Tuberculosis": "Consult a doctor for testing and full treatment.",
    "Common Cold": "Rest, drink warm fluids, and monitor symptoms.",
    "Pneumonia": "Seek medical care if breathing difficulty or chest pain occurs.",
    "Dimorphic hemmorhoids(piles)": "Increase fiber intake and consult a doctor if pain persists.",
    "Heart attack": "Call emergency medical help immediately.",
    "Varicose veins": "Avoid standing for long periods and seek specialist advice.",
    "Hypothyroidism": "Consult a doctor for thyroid hormone evaluation.",
    "Hyperthyroidism": "Get thyroid tests done and consult an endocrinologist.",
    "Hypoglycemia": "Take sugar immediately if conscious and consult a doctor.",
    "Osteoarthristis": "Do light exercise and consult an orthopedician.",
    "Arthritis": "Seek evaluation for joint pain and swelling.",
    "Vertigo (Paroxysmal Positional Vertigo)": "Avoid sudden head movement and consult a doctor.",
    "Acne": "Keep skin clean and consult a dermatologist if severe.",
    "Urinary tract infection": "Drink water and seek treatment if burning urination continues.",
    "Psoriasis": "Avoid skin triggers and consult a dermatologist.",
    "Impetigo": "Maintain hygiene and seek skin treatment."
}